fusermount ss provided by package "fuse", but pyfuse3 requires package "fuse3",
which provides command fusermount3, not fusermount.

--- a/src/borg/helpers/fs.py
+++ b/src/borg/helpers/fs.py
@@ -351,7 +351,7 @@
 
     env = prepare_subprocess_env(system=True)
     try:
-        rc = subprocess.call(['fusermount', '-u', mountpoint], env=env)
+        rc = subprocess.call(['fusermount3', '-u', mountpoint], env=env)
     except FileNotFoundError:
         rc = subprocess.call(['umount', mountpoint], env=env)
     set_ec(rc) 
