Source: https://github.com/mopidy/mopidy/commit/6c63054fcdb41394e0073a3af8972a589e2a3c59.patch
--
From 6c63054fcdb41394e0073a3af8972a589e2a3c59 Mon Sep 17 00:00:00 2001
From: Stein Magnus Jodal <stein.magnus.jodal@oda.com>
Date: Sun, 13 Oct 2024 21:42:01 +0200
Subject: [PATCH] Work around changed argparse errors in Python 3.12.7

Proobably caused by https://github.com/python/cpython/pull/124306
---
 tests/test_commands.py | 17 +++++++++--------
 1 file changed, 9 insertions(+), 8 deletions(-)

diff --git a/tests/test_commands.py b/tests/test_commands.py
index 7fe289a7c..0578c3d0f 100644
--- a/tests/test_commands.py
+++ b/tests/test_commands.py
@@ -1,4 +1,5 @@
 import argparse
+import re
 import unittest
 from unittest import mock
 
@@ -178,10 +179,10 @@ def test_missing_positionals(self):
         with pytest.raises(SystemExit):
             cmd.parse([], prog="foo")
 
-        self.exit_mock.assert_called_once_with(
-            1,
-            "the following arguments are required: bar, _args",
-            "usage: foo bar",
+        assert self.exit_mock.call_count == 1
+        assert re.match(
+            r"the following arguments are required: bar",
+            self.exit_mock.call_args[0][1],
         )
 
     def test_missing_positionals_subcommand(self):
@@ -194,10 +195,10 @@ def test_missing_positionals_subcommand(self):
         with pytest.raises(SystemExit):
             cmd.parse(["bar"], prog="foo")
 
-        self.exit_mock.assert_called_once_with(
-            1,
-            "the following arguments are required: baz, _args",
-            "usage: foo bar baz",
+        assert self.exit_mock.call_count == 1
+        assert re.match(
+            r"the following arguments are required: baz",
+            self.exit_mock.call_args[0][1],
         )
 
     def test_unknown_command(self):
